---
layout: cv
title: Owen Morales
---

Engineer, Data Scientis, Entusiast.

<div id="webaddress">
<a href="morales.owen@icloud.com">morales.owen@icloud.com</a>
| <a href="https://omora14.github.io/owendevhub/portfolio/">Portfolio</a>
</div>

### Specialized

ML/DL, Analysis, Data Visualization, Web Development, Cloud Computing, Backend

## Experience

`May 2024 – Present`
__BYU__, Rexburg, ID  
_Software Engineer_

- Automated tasks with TypeScript and Java, saving 5,000 staff hours annually, deployed on Heroku.
- Created tools with JavaScript, Bootstrap, Node.js, and iPaaS, saving $52,000 in labor costs.
- Managed 100+ projects with RESTful APIs, Spring Boot, and Express.js, enhancing the experience for 50,000+ users.

`Sep 2023 – May 2024`
__CCS Global Tech__, Poway, CA  
_Data Lead_

- Optimized data operations using SQL, Power BI, Snowflake, ETL, .NET, and Python, resulting in cost savings of $100,000 p/y.
- Designed and deployed a CRM with R reports, boosting staff productivity by 34%.

`Sep 2023 – May 2024`
__Twilio__, Remote, CA  
_Software Engineer_

- Improved UX/UI by implementing new features and fixing bugs using JavaScript and Java, contributing to 13% of KPI improvements.
- Reduced security incidents by 3% through the application of OWASP standards.
- Enhanced SaaS and web service performance by 15%, resulting in faster load times.

`Feb 2022 – Sep 2023`
__Verizon__, Remote, NY  
_Engineer Lead_

- Led 12 engineers at Verizon's Visible, reducing project timelines by 34% while serving as TP for 1 year.
- Integrated MTAS/MSAT, Orchestration Plan (OP), and Salesforce, saving $148,000 annually.
- Developed C#/ASP .NET tool for JIRA ticket management, boosting team efficiency by 78%.

## Education

`2022 - Present`
__Brigham Young University.__

## Awards

`2024`
Merit Scholarship, *BYU*, Idaho, USA

`2022`
TP (Top Performer), *Verizon*, New York, USA

### Footer

Last updated: Oct 2024